[project]
name = "transformer-from-scratch"
version = "0.1.0"
description = "Implementing the transformer from scratch using PyTorch"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "ruff>=0.13.0",
    "torch>=2.8.0",
]
